# Generated by Django 4.2.7 on 2026-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("AC Repair", "AC Repair"),
                            ("AC Servicing", "AC Servicing"),
                            ("AC Installation", "AC Installation"),
                            ("AC Uninstallation", "AC Uninstallation"),
                            ("AC Gas Filling", "AC Gas Filling"),
                            ("Split AC Service", "Split AC Service"),
                            ("Window AC Service", "Window AC Service"),
                            ("Refrigerator Repair", "Refrigerator Repair"),
                            ("Deep Freezer Repair", "Deep Freezer Repair"),
                            ("Commercial Freezer Repair", "Commercial Freezer Repair"),
                            ("Chiller Repair", "Chiller Repair"),
                            ("Cold Room Repair", "Cold Room Repair"),
                            ("Cold Storage Repair", "Cold Storage Repair"),
                            ("Washing Machine Repair", "Washing Machine Repair"),
                            (
                                "Washing Machine Installation",
                                "Washing Machine Installation",
                            ),
                            ("Water Cooler Repair", "Water Cooler Repair"),
                            ("Water Dispenser Repair", "Water Dispenser Repair"),
                            ("Geyser Repair", "Geyser Repair"),
                            ("Geyser Installation", "Geyser Installation"),
                            ("Microwave Oven Repair", "Microwave Oven Repair"),
                            ("Electric Oven Repair", "Electric Oven Repair"),
                            ("Induction Repair", "Induction Repair"),
                            ("Vehicle AC Repair", "Vehicle AC Repair"),
                            ("Vehicle AC Gas Filling", "Vehicle AC Gas Filling"),
                            ("Fan Repair", "Fan Repair"),
                            ("Inverter Repair", "Inverter Repair"),
                            ("Stabilizer Repair", "Stabilizer Repair"),
                            ("LED TV Repair", "LED TV Repair"),
                        ],
                        max_length=100,
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                ("problem_description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField(default=0)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("eSewa", "eSewa"),
                            ("Fonepay", "Fonepay"),
                            ("Card", "Debit/Credit Card"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("payment_status", models.CharField(default="Pending", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Assigned", "Assigned"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "technician_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "technician_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("technician_notes", models.TextField(blank=True, null=True)),
                ("customer_feedback", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("is_emergency", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
